name: Auto Build
on:
  push:
    paths:
      - '*.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip
        run: |
          # 强制找当前目录下唯一的 zip 文件并解压
          find . -maxdepth 1 -name "*.zip" | xargs -I {} unzip -o {}

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: app/build/outputs/apk/debug/*.apk
